config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'faq' => 'common_questions#index'
  get 'about' => 'about#index'
  get 'terms' => 'terms#index'
  get 'users' => 'users#index'

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/login' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  resources :users
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :user_id, :presence => true

  validates_uniqueness_of :user_id, :scope => :project_id

  validates :role, presence: true

  enum role: [:member, :owner]
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authorize, :set_project, :owner


  def index
    @memberships = Membership.all
    @membership = Membership.new
  end

  def new
    @membership = Membership.new
  end

  def create
    @membership = Membership.create(membership_params)
    @membership.user_id = params[:membership][:user_id]
    @membership.project_id = @project.id
    respond_to do |format|
      if @membership.save
        format.html { redirect_to project_memberships_path, notice: "#{@membership.user.full_name} was successfully added" }
        format.json { render :index, status: :created, location: @project }
      else
        format.html { render :index }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end

  end

  def update
    @membership = Membership.find(params[:id])
      if @membership.role == "owner" && @project.memberships.where(role: 1).count == 1
        redirect_to project_memberships_path(@project), alert: "Projects much have at least one owner"
      elsif @membership.update(membership_params)
        redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was successfully updated"
      end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.project_id = @project.id
    @membership.destroy
    if current_user.owner?(@project)
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was successfully removed"
    else
      redirect_to projects_path(@project), notice: "#{@membership.user.full_name} was successfully removed"
    end
  end


  private
  def membership_params
    params.require(:membership).permit(:role, :user_id, :project_id)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

  def owner
    unless current_user.admin? || @project.users.include?(current_user)
        redirect_to projects_path, alert: "You do not have access to that project"
    end
  end
end

app/views/memberships/index.html.erb
<% if notice %>
<p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger" id="alert"><%= alert  %></p>
<% end %>

<div class="page-header">
  <h1><%= "#{@project.name}: Manage Members" %></h1>
  <ol class="breadcrumb">
    <li><a href="/projects">Projects</a></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li class="active">Memberships</li>
  </ol>
</div>
<%= render partial: "/shared/errors", locals: {object: @membership} %>

<% if current_user.owner?(@project) || current_user.admin? %>

<div class="well form-inline">

  <%= form_for [@project, @membership] do |f| %>

  <div class="form-group">
    <%= f.collection_select(:user_id, User.all, :id, :full_name, {prompt: true, include_blank: true}, {class: "form-control"}) %>
  </div>
  <div class="form-group">
    <%= f.select(:role, [["Member", :member],["Owner", :owner]], {include_blank: false}, {class: "form-control"}) %>
  </div>

  <%= f.submit 'Add a new member', :class => 'btn btn-primary'%>
  <% end %>
</div>

<div class="memberships">
  <% @project.memberships.each do |membership| %>
    <%= form_for([@project, membership], html: {:class => "form-inline"}) do |f| %>
    <div class="form-group col-md-2">
      <%= link_to membership.user.full_name, user_path(membership.user), class: "control-label" %>
    </div>
    <div class="form-group col-md-2">
      <%= f.select(:role, [["Member", :member],["Owner", :owner]], {include_blank: false}, {class: "form-control"}) %>
    </div>

    <%= f.submit 'Update', :class => 'btn btn-primary'%>
    <% if membership.role == "owner" && @project.memberships.where(role: 1).count == 1 %>
      <span>You are the last owner </span>
    <% else %>
    <%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden=true></span>'.html_safe, project_membership_path(@project, membership), method: :delete, data: { confirm: "Are you sure you want to delete that?"} %>
    <br/>
    <% end %>
    <% end %>
  <% end %>
  <% else %>
    <table class="table">
      <tbody>
        <% @project.memberships.each do |membership| %>
        <tr>
          <td>
            <%= membership.user.full_name %>
          </td>
          <td>
            <% if membership.user.id == current_user.id %>
              <%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden=true></span>'.html_safe, project_membership_path(@project, membership), method: :delete, data: { confirm: "Are you sure you want to delete that?"} %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>