config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'faq' => 'common_questions#index'
  get 'about' => 'about#index'
  get 'terms' => 'terms#index'
  get 'users' => 'users#index'

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/login' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  resources :users
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :comments
  has_many :users, through: :comments

  validates :description, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorize, :set_project
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :owner

  def index
    @tasks = @project.tasks.all
  end

  def show
    @comments = Comment.where(:task_id => @task.id)
    @comment = Comment.new
  end

  def new
    @task = @project.tasks.build
  end

  def edit
  end

  def create
    @task = @project.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
          format.html {render :edit }
          format.json {render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :due_date, :complete, :project_id)
    end


    def set_project
      @project = Project.find(params[:project_id])
    end


    def owner
      unless current_user.admin? ||  @project.users.include?(current_user)
          redirect_to projects_path, alert: "You do not have access to that project"
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@project, @task], html: {:class => "form-horizontal"})  do |f| %>

<%= render partial: "/shared/errors", locals: {object: @task} %>

<div class="form-group">
  <div class="field">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="form-controls col-md-4">
      <%= f.text_field :description, :class => 'form-control'%>
    </div>
  </div>
</div>

<div class="form-group">
    <%= f.label :due_date, :class => 'control-label col-md-2' %>
    <div class="col-md-4">
    <%= f.date_select :due_date, :class => 'form-control' %>
  </div>
</div>
<% unless @task.id == nil %>
<div class="form-group">
  <div class="col-md-offset-2 col-md-4">
    <%= f.check_box :complete %>
    <%= f.label :complete %>
  </div>
</div>
<% end %>
<div class="form-group">
  <div class="col-md-offset-2 col-md-4">
    <% if @task.id == nil %>
      <%= f.submit 'Create Task', :class => 'btn btn-primary' %>
      <a class="btn btn-default" href="/projects">Cancel</a>
    <% else %>
      <%= f.submit 'Update Task', :class => 'btn btn-primary' %>
      <%= link_to 'Delete Task', project_task_path(@project, @task), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
      <a class="btn btn-default" href="/projects">Cancel</a>
    <% end %>

  </div>
</div>

<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>



<%= render 'form' %>

app/views/tasks/index.html.erb
<% if notice %>
  <p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>

<ol class="breadcrumb">
  <li><%= link_to "Projects", projects_path %>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class="active">Tasks</li>
</ol>
<div class="page-header">
  <div class="pull-right">
    <%= link_to "New Task", new_project_task_path(@project), class: "btn btn-info" %>
  </div>
  <h1>Tasks for <%= @project.name %></h1>
</div>
<% if @project.tasks.count >= 1 %>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th>Complete</th>
        <th>Due</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%=  link_to task.description, project_task_path(@project, task) %> <span class="badge"> <%= Comment.where(:task_id => task.id).count %></span></td>
          <td><%=  task.complete? %></td>
          <td><%= task.due_date.strftime("%A %D") %></td>
          <td class="text-right">
            <%= link_to "Edit", edit_project_task_path(@project, task), class: "btn btn-info" %>
            <%= link_to '<span class="glyphicon glyphicon-remove" aria-hidden=true></span>'.html_safe, project_task_path(@project, task), method: :delete, data: { confirm: "Are you sure you want to delete that?"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  No tasks for this project yet!
<% end %>
<br>

app/views/tasks/new.html.erb
<div class="page-header">
  <h1>New Task</h1>
</div>
<ol class="breadcrumb">
  <li><a href="/tasks">Tasks</a></li>
  <li class="active">New Task</li>
</ol>
<%= render 'form' %>

app/views/tasks/show.html.erb
<% if notice %>

<p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>
<ol class="breadcrumb">
  <li> <%= link_to "Projects", projects_path(@project)  %></li>
  <li> <%= link_to @project.name, project_path(@project) %></li>
  <li><%= link_to "Tasks", project_tasks_path(@project) %></li>
  <li class="active"> <%= @task.description %> </li>
</ol>
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_project_task_path(@project, @task), class: 'btn btn-info' %>
  </div>
  <h1><%= @task.description %></h1>
</div>



<p>
  <strong>Due on:</strong>
  <%= @task.due_date.strftime("%m/%d/%Y") %>

</p>

<!-- <p>
  <strong>Complete:</strong>
  <%= @task.complete? %>
</p> -->
<h2>Comments</h2>


<% @comments.each do |comment| %>
  <div class="row">
    <div class="col-md-3">
    <%= link_to User.find(comment.user_id).full_name, user_path(comment.user_id) %><br>
    <div class="text-muted">
      <%= time_ago_in_words(comment.created_at) %> ago
    </div>
    </div>
    <div class="col-md-9">
      <%= comment.description %>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-md-offset-3 col-md-9">
    <%= form_for([@project,@task, @comment]) do |f| %>
    <div class="form-group">
      <%= f.text_area :description, size: "40x5", class: "form-control" %>
    </div>

    <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>