config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'faq' => 'common_questions#index'
  get 'about' => 'about#index'
  get 'terms' => 'terms#index'
  get 'users' => 'users#index'

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/login' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  resources :users
  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  validates :name, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authorize
  before_action :owner, only: [:edit, :update]


  def index
    if current_user.admin?
      @projects = Project.all
    else
      @projects = current_user.projects
    end
  end

  def show
    @project = Project.find(params[:id])
    unless current_user.admin? || @project.users.include?(current_user )
        redirect_to projects_path, alert: "You do not have access to that project"
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_tasks_path(@project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
    @membership = Membership.create(project_id: @project.id, user_id: current_user.id, role: 1)
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully deleted'
  end


  private
  def project_params
    params.require(:project).permit(:name)
  end

  def owner
    unless current_user.admin? || current_user.owner?(@project) || @project.users.include?(current_user)
        redirect_to projects_path, alert: "You do not have access to that project"
    end
  end

end

app/views/projects/_form.html.erb
<%= form_for(@project, html: {:class => "form-horizontal"})  do |f| %>
<%= render partial: "/shared/errors", locals: {object: @project} %>

<div class="form-group">
  <div class="field">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="form-controls col-md-4">
      <%= f.text_field :name, :class => 'form-control'%>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="col-md-offset-2 col-md-4">
    <% if @project.id == nil %>
    <%= f.submit 'Create Project', :class => 'btn btn-primary' %>
    <a class="btn btn-default" href="/projects">Cancel</a>
    <% else %>
    <%= f.submit 'Update Project', :class => 'btn btn-primary' %>
    <%= link_to 'Delete Project', @project, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
    <a class="btn btn-default" href="/projects">Cancel</a>
    <% end %>

  </div>
</div>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit Project</h1>
</div>
<ol class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li class="active"><%= @project.name %></li>
</ol>
<%= render 'form' %>

app/views/projects/index.html.erb
<% if notice %>
<p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger" id="alert"><%= alert  %></p>
<% end %>
<div class="page-header">
  <div class="pull-right">
    <a class="btn btn-info" href="/projects/new">New Project</a>
  </div>
  <h1>Projects</h1>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td><%= link_to  project.name, project %></td>
      <td><%= link_to  project.tasks.count, project_tasks_path(project) %></td>

    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/new.html.erb
<% if notice %>
  <p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>
<div class="page-header">
  <h1>Create Project</h1>
</div>
<ol class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li class="active">New Project</li>
</ol>
<%= render 'form' %>

app/views/projects/show.html.erb
<% if notice %>

<p class="alert alert-success" id="notice"><%= notice  %></p>
<% end %>

<div class="page-header">
  <ol class="breadcrumb">
    <li><a href="/projects">Projects</a></li>
    <li class="active"><%= @project.name %></li>
  </ol>
  <% if current_user.owner?(@project) || current_user.admin?  %>
    <div class="pull-right">
      <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-info" %>
    </div>
  <% end %>
  <h1><%= @project.name %></h1>
</div>


<% if @project.tasks.count == 1 %>
<%= link_to "#{@project.tasks.count} task", project_tasks_path(@project) %>
<% else %>
<%= link_to "#{@project.tasks.count} tasks", project_tasks_path(@project) %>
<% end %>

<br/>
<%= link_to "#{@project.users.count} members", project_memberships_path(@project) %>


<% if current_user.owner?(@project) || current_user.admin?  %>
<div class="well">
  <h4>Delete</h4>
  <div>
    Deleting this project will also delete <%= @project.memberships.count %> memberships, <%= @project.tasks.count %> tasks and associated comments.
  </div>
  <%= link_to 'Delete', @project, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<% end %>